export enum TransactionErrors {
  REFERENCE_ACCOUNT_NOT_FOUND = 'REFERENCE_ACCOUNT_NOT_FOUND',
  REFERENCE_CATEGORY_NOT_FOUND = 'REFERENCE_CATEGORY_NOT_FOUND',
  REFERENCE_CATEGORY_WRONG_TYPE = 'REFERENCE_CATEGORY_WRONG_TYPE',
  REFERENCE_SUBCATEGORY_NOT_FOUND = 'REFERENCE_SUBCATEGORY_NOT_FOUND',
  REFERENCE_SUBCATEGORY_NOT_IN_CATEGORY = 'REFERENCE_SUBCATEGORY_NOT_IN_CATEGORY',
  AMOUNT_NOT_ZERO_OR_NEGATIVE = 'AMOUNT_NOT_ZERO_OR_NEGATIVE',
  EFFECTIVATED_DATE_NOT_BE_NULL = 'EFFECTIVATED_DATE_NOT_BE_NULL',
  TRANSACTION_DUE_DATE_NOT_AFTER_ENTRY_DATE = 'TRANSACTION_DUE_DATE_NOT_AFTER_ENTRY_DATE',
  TRANSACTION_EFFECTIVATED_DATE_NOT_AFTER_ENTRY_DATE = 'TRANSACTION_EFFECTIVATED_DATE_NOT_AFTER_ENTRY_DATE',
}
