export enum TransactionErrors {
  REFERENCE_ACCOUNT_NOT_FOUND = 'REFERENCE_ACCOUNT_NOT_FOUND',
  AMOUNT_NOT_ZERO_OR_NEGATIVE = 'AMOUNT_NOT_ZERO_OR_NEGATIVE',
  EFFECTIVATED_DATE_NOT_BE_NULL = 'EFFECTIVATED_DATE_NOT_BE_NULL',
  TRANSACTION_DUE_DATE_NOT_AFTER_ENTRY_DATE = 'TRANSACTION_DUE_DATE_NOT_AFTER_ENTRY_DATE',
  TRANSACTION_EFFECTIVATED_DATE_NOT_AFTER_ENTRY_DATE = 'TRANSACTION_EFFECTIVATED_DATE_NOT_AFTER_ENTRY_DATE',
}
