export enum ValueObjectErrors {
  // Money
  MONEY_CENTS_NOT_INTEGER = 'MONEY_CENTS_NOT_INTEGER',
  MONEY_NOT_FINITE = 'MONEY_NOT_FINITE',
  // Effectivated
  EFFECTIVATED_DATE_NOT_BE_NULL = 'EFFECTIVATED_DATE_NOT_BE_NULL',
  // ReportingPeriod
  END_DATE_NOT_AFTER_START_DATE = 'END_DATE_NOT_AFTER_START_DATE',
}
